version: '3'

services:
    ai-server:
        build: ./ai-server
        restart: unless-stopped
        volumes:
            - ./ai-server:/app
            - ./ai-data:/data
        ports:
            - 5000:5000
        depends_on:
            - db
    learner-server:
        build: ./learner-server
        restart: unless-stopped
        volumes:
            - ./learner-server:/app
            - ./ai-data:/data
        ports:
            - 5010:5010
        depends_on:
            - db
    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres_user
            - POSTGRES_PASSWORD=postgres_pass